[versions]
android-gradle-plugin = "7.3.1"
kotlin = "1.7.20"
gradle-versions-plugin = "0.42.0"

sdk-platform-compile = "33"
sdk-platform-min = "21"
sdk-platform-target = "33"
sdk-ndk = "25.1.8937393"
sdk-cmake = "3.22.1"

coroutines = "1.6.4"
serialization = "1.4.1"
# Gradle bundles Kotlin 1.6, make sure to not pull newer version through dependencies
coroutines-gradle = "1.6.4"

androidx-appcompat = "1.5.1"
androidx-collection = "1.2.0"
androidx-core = "1.9.0"
androidx-coordinatorlayout = "1.2.0"
androidx-fragment = "1.5.3"
androidx-gridlayout = "1.0.0"
androidx-lifecycle = "2.5.1"
androidx-navigation = "2.5.2"
androidx-recyclerview = "1.2.1"
androidx-preference = "1.2.0"
androidx-swiperefreshlayout = "1.1.0"
androidx-viewpager2 = "1.0.0"
androidx-work = "2.7.1"

commons-text = "1.9"
fastscroll = "2.1.0"
leakcanary = "2.9.1"
material = "1.6.1"
publicsuffixlist = "106.0.5"
timber = "5.0.1"
threetenabp = "1.4.2"

junit = "4.13.2"

serialization-bencode = "0.1"
tremotesf-plugin = "0.1"

[libraries]
android-gradle-plugin-api = { module = "com.android.tools.build:gradle-api", version.ref = "android-gradle-plugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-versions-plugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "gradle-versions-plugin" }

coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
coroutines-gradle-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines-gradle" }
coroutines-gradle-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "coroutines-gradle" }

serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
serialization-bencode = { module = "org.equeim:kotlinx-serialization-bencode", version.ref = "serialization-bencode" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-collection = { module = "androidx.collection:collection-ktx", version.ref = "androidx-collection" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "androidx-coordinatorlayout" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "androidx-gridlayout" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx-viewpager2" }
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }

commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
fastscroll = { module = "io.github.l4digital:fastscroll", version.ref = "fastscroll" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
material = { module = "com.google.android.material:material", version.ref = "material" }
publicsuffixlist = { module = "org.mozilla.components:lib-publicsuffixlist", version.ref = "publicsuffixlist" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
threetenabp = { module = "com.jakewharton.threetenabp:threetenabp", version.ref = "threetenabp" }

junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-plugin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
androidx-navigation = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation" }
tremotesf = { id = "org.equeim.tremotesf", version.ref = "tremotesf-plugin" }
