/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.equeim.libtremotesf;

public class libtremotesf {
  public static TorrentData moveFrom(TorrentData other) {
    return new TorrentData(libtremotesfJNI.moveFrom__SWIG_0(TorrentData.getCPtr(other), other), true);
  }

  public static TorrentFile moveFrom(TorrentFile other) {
    return new TorrentFile(libtremotesfJNI.moveFrom__SWIG_1(TorrentFile.getCPtr(other), other), true);
  }

  public static Peer moveFrom(Peer other) {
    return new Peer(libtremotesfJNI.moveFrom__SWIG_2(Peer.getCPtr(other), other), true);
  }

}
