/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.equeim.libtremotesf;

public class libtremotesf {
  public static TorrentData moveFromVector(TorrentData other) {
    return new TorrentData(libtremotesfJNI.moveFromVector__SWIG_0(TorrentData.getCPtr(other), other), true);
  }

  public static TorrentFile moveFromVector(TorrentFile other) {
    return new TorrentFile(libtremotesfJNI.moveFromVector__SWIG_1(TorrentFile.getCPtr(other), other), true);
  }

  public static Peer moveFromVector(Peer other) {
    return new Peer(libtremotesfJNI.moveFromVector__SWIG_2(Peer.getCPtr(other), other), true);
  }

}
