/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.equeim.libtremotesf;

public class Peer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Peer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Peer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Peer obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtremotesfJNI.delete_Peer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getAddress() {
    return libtremotesfJNI.Peer_address_get(swigCPtr, this);
}

  public String getClient() {
    return libtremotesfJNI.Peer_client_get(swigCPtr, this);
}

  public long getDownloadSpeed() {
    return libtremotesfJNI.Peer_downloadSpeed_get(swigCPtr, this);
  }

  public long getUploadSpeed() {
    return libtremotesfJNI.Peer_uploadSpeed_get(swigCPtr, this);
  }

  public double getProgress() {
    return libtremotesfJNI.Peer_progress_get(swigCPtr, this);
  }

  public String getFlags() {
    return libtremotesfJNI.Peer_flags_get(swigCPtr, this);
}

}
