/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.equeim.libtremotesf;

public final class RpcConnectionState {
  public final static int Disconnected = 0;
  public final static int Connecting = Disconnected + 1;
  public final static int Connected = Connecting + 1;
}

