/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.equeim.libtremotesf;

public final class RpcError {
  public final static int NoError = 0;
  public final static int TimedOut = NoError + 1;
  public final static int ConnectionError = TimedOut + 1;
  public final static int AuthenticationError = ConnectionError + 1;
  public final static int ParseError = AuthenticationError + 1;
  public final static int ServerIsTooNew = ParseError + 1;
  public final static int ServerIsTooOld = ServerIsTooNew + 1;
}

