/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.equeim.libtremotesf;

public class TorrentData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TorrentData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TorrentData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtremotesfJNI.delete_TorrentData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getId() {
    return libtremotesfJNI.TorrentData_id_get(swigCPtr, this);
  }

  public String getHashString() {
    return libtremotesfJNI.TorrentData_hashString_get(swigCPtr, this);
}

  public String getName() {
    return libtremotesfJNI.TorrentData_name_get(swigCPtr, this);
}

  public String getMagnetLink() {
    return libtremotesfJNI.TorrentData_magnetLink_get(swigCPtr, this);
}

  public String getErrorString() {
    return libtremotesfJNI.TorrentData_errorString_get(swigCPtr, this);
}

  public TorrentData.Status getStatus() {
    return TorrentData.Status.swigToEnum(libtremotesfJNI.TorrentData_status_get(swigCPtr, this));
  }

  public int getQueuePosition() {
    return libtremotesfJNI.TorrentData_queuePosition_get(swigCPtr, this);
  }

  public long getTotalSize() {
    return libtremotesfJNI.TorrentData_totalSize_get(swigCPtr, this);
  }

  public long getCompletedSize() {
    return libtremotesfJNI.TorrentData_completedSize_get(swigCPtr, this);
  }

  public long getLeftUntilDone() {
    return libtremotesfJNI.TorrentData_leftUntilDone_get(swigCPtr, this);
  }

  public long getSizeWhenDone() {
    return libtremotesfJNI.TorrentData_sizeWhenDone_get(swigCPtr, this);
  }

  public double getPercentDone() {
    return libtremotesfJNI.TorrentData_percentDone_get(swigCPtr, this);
  }

  public double getRecheckProgress() {
    return libtremotesfJNI.TorrentData_recheckProgress_get(swigCPtr, this);
  }

  public int getEta() {
    return libtremotesfJNI.TorrentData_eta_get(swigCPtr, this);
  }

  public boolean getMetadataComplete() {
    return libtremotesfJNI.TorrentData_metadataComplete_get(swigCPtr, this);
  }

  public long getDownloadSpeed() {
    return libtremotesfJNI.TorrentData_downloadSpeed_get(swigCPtr, this);
  }

  public long getUploadSpeed() {
    return libtremotesfJNI.TorrentData_uploadSpeed_get(swigCPtr, this);
  }

  public boolean getDownloadSpeedLimited() {
    return libtremotesfJNI.TorrentData_downloadSpeedLimited_get(swigCPtr, this);
  }

  public int getDownloadSpeedLimit() {
    return libtremotesfJNI.TorrentData_downloadSpeedLimit_get(swigCPtr, this);
  }

  public boolean getUploadSpeedLimited() {
    return libtremotesfJNI.TorrentData_uploadSpeedLimited_get(swigCPtr, this);
  }

  public int getUploadSpeedLimit() {
    return libtremotesfJNI.TorrentData_uploadSpeedLimit_get(swigCPtr, this);
  }

  public long getTotalDownloaded() {
    return libtremotesfJNI.TorrentData_totalDownloaded_get(swigCPtr, this);
  }

  public long getTotalUploaded() {
    return libtremotesfJNI.TorrentData_totalUploaded_get(swigCPtr, this);
  }

  public double getRatio() {
    return libtremotesfJNI.TorrentData_ratio_get(swigCPtr, this);
  }

  public double getRatioLimit() {
    return libtremotesfJNI.TorrentData_ratioLimit_get(swigCPtr, this);
  }

  public TorrentData.RatioLimitMode getRatioLimitMode() {
    return TorrentData.RatioLimitMode.swigToEnum(libtremotesfJNI.TorrentData_ratioLimitMode_get(swigCPtr, this));
  }

  public int getSeeders() {
    return libtremotesfJNI.TorrentData_seeders_get(swigCPtr, this);
  }

  public int getWebSeeders() {
    return libtremotesfJNI.TorrentData_webSeeders_get(swigCPtr, this);
  }

  public int getLeechers() {
    return libtremotesfJNI.TorrentData_leechers_get(swigCPtr, this);
  }

  public int getPeersLimit() {
    return libtremotesfJNI.TorrentData_peersLimit_get(swigCPtr, this);
  }

  public long getAddedDateTime() {
    return libtremotesfJNI.TorrentData_addedDateTime_get(swigCPtr, this);
  }

  public long getActivityDateTime() {
    return libtremotesfJNI.TorrentData_activityDateTime_get(swigCPtr, this);
  }

  public long getDoneDateTime() {
    return libtremotesfJNI.TorrentData_doneDateTime_get(swigCPtr, this);
  }

  public TorrentData.IdleSeedingLimitMode getIdleSeedingLimitMode() {
    return TorrentData.IdleSeedingLimitMode.swigToEnum(libtremotesfJNI.TorrentData_idleSeedingLimitMode_get(swigCPtr, this));
  }

  public int getIdleSeedingLimit() {
    return libtremotesfJNI.TorrentData_idleSeedingLimit_get(swigCPtr, this);
  }

  public String getDownloadDirectory() {
    return libtremotesfJNI.TorrentData_downloadDirectory_get(swigCPtr, this);
}

  public String getComment() {
    return libtremotesfJNI.TorrentData_comment_get(swigCPtr, this);
}

  public String getCreator() {
    return libtremotesfJNI.TorrentData_creator_get(swigCPtr, this);
}

  public long getCreationDateTime() {
    return libtremotesfJNI.TorrentData_creationDateTime_get(swigCPtr, this);
  }

  public TorrentData.Priority getBandwidthPriority() {
    return TorrentData.Priority.swigToEnum(libtremotesfJNI.TorrentData_bandwidthPriority_get(swigCPtr, this));
  }

  public boolean getHonorSessionLimits() {
    return libtremotesfJNI.TorrentData_honorSessionLimits_get(swigCPtr, this);
  }

  public boolean getSingleFile() {
    return libtremotesfJNI.TorrentData_singleFile_get(swigCPtr, this);
  }

  public boolean getTrackersAnnounceUrlsChanged() {
    return libtremotesfJNI.TorrentData_trackersAnnounceUrlsChanged_get(swigCPtr, this);
  }

  public TrackersVector getTrackers() {
    long cPtr = libtremotesfJNI.TorrentData_trackers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TrackersVector(cPtr, false);
  }

  public TorrentData() {
    this(libtremotesfJNI.new_TorrentData(), true);
  }

  public enum Status {
    Paused,
    Downloading,
    Seeding,
    StalledDownloading,
    StalledSeeding,
    QueuedForDownloading,
    QueuedForSeeding,
    Checking,
    QueuedForChecking,
    Errored;

    public final int swigValue() {
      return swigValue;
    }

    public static Status swigToEnum(int swigValue) {
      Status[] swigValues = Status.class.getEnumConstants();
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (Status swigEnum : swigValues)
        if (swigEnum.swigValue == swigValue)
          return swigEnum;
      throw new IllegalArgumentException("No enum " + Status.class + " with value " + swigValue);
    }

    @SuppressWarnings("unused")
    private Status() {
      this.swigValue = SwigNext.next++;
    }

    @SuppressWarnings("unused")
    private Status(int swigValue) {
      this.swigValue = swigValue;
      SwigNext.next = swigValue+1;
    }

    @SuppressWarnings("unused")
    private Status(Status swigEnum) {
      this.swigValue = swigEnum.swigValue;
      SwigNext.next = this.swigValue+1;
    }

    private final int swigValue;

    private static class SwigNext {
      private static int next = 0;
    }
  }

  public enum Priority {
    LowPriority(-1),
    NormalPriority,
    HighPriority;

    public final int swigValue() {
      return swigValue;
    }

    public static Priority swigToEnum(int swigValue) {
      Priority[] swigValues = Priority.class.getEnumConstants();
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (Priority swigEnum : swigValues)
        if (swigEnum.swigValue == swigValue)
          return swigEnum;
      throw new IllegalArgumentException("No enum " + Priority.class + " with value " + swigValue);
    }

    @SuppressWarnings("unused")
    private Priority() {
      this.swigValue = SwigNext.next++;
    }

    @SuppressWarnings("unused")
    private Priority(int swigValue) {
      this.swigValue = swigValue;
      SwigNext.next = swigValue+1;
    }

    @SuppressWarnings("unused")
    private Priority(Priority swigEnum) {
      this.swigValue = swigEnum.swigValue;
      SwigNext.next = this.swigValue+1;
    }

    private final int swigValue;

    private static class SwigNext {
      private static int next = 0;
    }
  }

  public enum RatioLimitMode {
    GlobalRatioLimit,
    SingleRatioLimit,
    UnlimitedRatio;

    public final int swigValue() {
      return swigValue;
    }

    public static RatioLimitMode swigToEnum(int swigValue) {
      RatioLimitMode[] swigValues = RatioLimitMode.class.getEnumConstants();
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (RatioLimitMode swigEnum : swigValues)
        if (swigEnum.swigValue == swigValue)
          return swigEnum;
      throw new IllegalArgumentException("No enum " + RatioLimitMode.class + " with value " + swigValue);
    }

    @SuppressWarnings("unused")
    private RatioLimitMode() {
      this.swigValue = SwigNext.next++;
    }

    @SuppressWarnings("unused")
    private RatioLimitMode(int swigValue) {
      this.swigValue = swigValue;
      SwigNext.next = swigValue+1;
    }

    @SuppressWarnings("unused")
    private RatioLimitMode(RatioLimitMode swigEnum) {
      this.swigValue = swigEnum.swigValue;
      SwigNext.next = this.swigValue+1;
    }

    private final int swigValue;

    private static class SwigNext {
      private static int next = 0;
    }
  }

  public enum IdleSeedingLimitMode {
    GlobalIdleSeedingLimit,
    SingleIdleSeedingLimit,
    UnlimitedIdleSeeding;

    public final int swigValue() {
      return swigValue;
    }

    public static IdleSeedingLimitMode swigToEnum(int swigValue) {
      IdleSeedingLimitMode[] swigValues = IdleSeedingLimitMode.class.getEnumConstants();
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (IdleSeedingLimitMode swigEnum : swigValues)
        if (swigEnum.swigValue == swigValue)
          return swigEnum;
      throw new IllegalArgumentException("No enum " + IdleSeedingLimitMode.class + " with value " + swigValue);
    }

    @SuppressWarnings("unused")
    private IdleSeedingLimitMode() {
      this.swigValue = SwigNext.next++;
    }

    @SuppressWarnings("unused")
    private IdleSeedingLimitMode(int swigValue) {
      this.swigValue = swigValue;
      SwigNext.next = swigValue+1;
    }

    @SuppressWarnings("unused")
    private IdleSeedingLimitMode(IdleSeedingLimitMode swigEnum) {
      this.swigValue = swigEnum.swigValue;
      SwigNext.next = this.swigValue+1;
    }

    private final int swigValue;

    private static class SwigNext {
      private static int next = 0;
    }
  }

}
