/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.equeim.libtremotesf;

public class TorrentDataVector extends java.util.AbstractList<TorrentData> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TorrentDataVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TorrentDataVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TorrentDataVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtremotesfJNI.delete_TorrentDataVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TorrentDataVector(TorrentData[] initialElements) {
    this();
    reserve(initialElements.length);

    for (TorrentData element : initialElements) {
      add(element);
    }
  }

  public TorrentDataVector(Iterable<TorrentData> initialElements) {
    this();
    for (TorrentData element : initialElements) {
      add(element);
    }
  }

  public TorrentData get(int index) {
    return doGet(index);
  }

  public TorrentData set(int index, TorrentData e) {
    return doSet(index, e);
  }

  public boolean add(TorrentData e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, TorrentData e) {
    modCount++;
    doAdd(index, e);
  }

  public TorrentData remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public TorrentDataVector() {
    this(libtremotesfJNI.new_TorrentDataVector__SWIG_0(), true);
  }

  public TorrentDataVector(TorrentDataVector other) {
    this(libtremotesfJNI.new_TorrentDataVector__SWIG_1(TorrentDataVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return libtremotesfJNI.TorrentDataVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libtremotesfJNI.TorrentDataVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libtremotesfJNI.TorrentDataVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libtremotesfJNI.TorrentDataVector_clear(swigCPtr, this);
  }

  public TorrentDataVector(int count, TorrentData value) {
    this(libtremotesfJNI.new_TorrentDataVector__SWIG_2(count, TorrentData.getCPtr(value), value), true);
  }

  private int doSize() {
    return libtremotesfJNI.TorrentDataVector_doSize(swigCPtr, this);
  }

  private void doAdd(TorrentData x) {
    libtremotesfJNI.TorrentDataVector_doAdd__SWIG_0(swigCPtr, this, TorrentData.getCPtr(x), x);
  }

  private void doAdd(int index, TorrentData x) {
    libtremotesfJNI.TorrentDataVector_doAdd__SWIG_1(swigCPtr, this, index, TorrentData.getCPtr(x), x);
  }

  private TorrentData doRemove(int index) {
    return new TorrentData(libtremotesfJNI.TorrentDataVector_doRemove(swigCPtr, this, index), true);
  }

  private TorrentData doGet(int index) {
    return new TorrentData(libtremotesfJNI.TorrentDataVector_doGet(swigCPtr, this, index), false);
  }

  private TorrentData doSet(int index, TorrentData val) {
    return new TorrentData(libtremotesfJNI.TorrentDataVector_doSet(swigCPtr, this, index, TorrentData.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    libtremotesfJNI.TorrentDataVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
