/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.equeim.libtremotesf;

public class ServerStats {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ServerStats(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ServerStats obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtremotesfJNI.delete_ServerStats(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long downloadSpeed() {
    return libtremotesfJNI.ServerStats_downloadSpeed(swigCPtr, this);
  }

  public long uploadSpeed() {
    return libtremotesfJNI.ServerStats_uploadSpeed(swigCPtr, this);
  }

  public SessionStats currentSession() {
    long cPtr = libtremotesfJNI.ServerStats_currentSession(swigCPtr, this);
    return (cPtr == 0) ? null : new SessionStats(cPtr, false);
  }

  public SessionStats total() {
    long cPtr = libtremotesfJNI.ServerStats_total(swigCPtr, this);
    return (cPtr == 0) ? null : new SessionStats(cPtr, false);
  }

}
