/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.equeim.libtremotesf;

public class ServerSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ServerSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ServerSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtremotesfJNI.delete_ServerSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean canRenameFiles() {
    return libtremotesfJNI.ServerSettings_canRenameFiles(swigCPtr, this);
  }

  public boolean canShowFreeSpaceForPath() {
    return libtremotesfJNI.ServerSettings_canShowFreeSpaceForPath(swigCPtr, this);
  }

  public String downloadDirectory() {
    return libtremotesfJNI.ServerSettings_downloadDirectory(swigCPtr, this);
}

  public boolean startAddedTorrents() {
    return libtremotesfJNI.ServerSettings_startAddedTorrents(swigCPtr, this);
  }

  public boolean renameIncompleteFiles() {
    return libtremotesfJNI.ServerSettings_renameIncompleteFiles(swigCPtr, this);
  }

  public boolean isIncompleteDirectoryEnabled() {
    return libtremotesfJNI.ServerSettings_isIncompleteDirectoryEnabled(swigCPtr, this);
  }

  public String incompleteDirectory() {
    return libtremotesfJNI.ServerSettings_incompleteDirectory(swigCPtr, this);
}

  public boolean isRatioLimited() {
    return libtremotesfJNI.ServerSettings_isRatioLimited(swigCPtr, this);
  }

  public double ratioLimit() {
    return libtremotesfJNI.ServerSettings_ratioLimit(swigCPtr, this);
  }

  public boolean isIdleSeedingLimited() {
    return libtremotesfJNI.ServerSettings_isIdleSeedingLimited(swigCPtr, this);
  }

  public int idleSeedingLimit() {
    return libtremotesfJNI.ServerSettings_idleSeedingLimit(swigCPtr, this);
  }

  public boolean isDownloadQueueEnabled() {
    return libtremotesfJNI.ServerSettings_isDownloadQueueEnabled(swigCPtr, this);
  }

  public int downloadQueueSize() {
    return libtremotesfJNI.ServerSettings_downloadQueueSize(swigCPtr, this);
  }

  public boolean isSeedQueueEnabled() {
    return libtremotesfJNI.ServerSettings_isSeedQueueEnabled(swigCPtr, this);
  }

  public int seedQueueSize() {
    return libtremotesfJNI.ServerSettings_seedQueueSize(swigCPtr, this);
  }

  public boolean isIdleQueueLimited() {
    return libtremotesfJNI.ServerSettings_isIdleQueueLimited(swigCPtr, this);
  }

  public int idleQueueLimit() {
    return libtremotesfJNI.ServerSettings_idleQueueLimit(swigCPtr, this);
  }

  public boolean isDownloadSpeedLimited() {
    return libtremotesfJNI.ServerSettings_isDownloadSpeedLimited(swigCPtr, this);
  }

  public int downloadSpeedLimit() {
    return libtremotesfJNI.ServerSettings_downloadSpeedLimit(swigCPtr, this);
  }

  public boolean isUploadSpeedLimited() {
    return libtremotesfJNI.ServerSettings_isUploadSpeedLimited(swigCPtr, this);
  }

  public int uploadSpeedLimit() {
    return libtremotesfJNI.ServerSettings_uploadSpeedLimit(swigCPtr, this);
  }

  public boolean isAlternativeSpeedLimitsEnabled() {
    return libtremotesfJNI.ServerSettings_isAlternativeSpeedLimitsEnabled(swigCPtr, this);
  }

  public int alternativeDownloadSpeedLimit() {
    return libtremotesfJNI.ServerSettings_alternativeDownloadSpeedLimit(swigCPtr, this);
  }

  public int alternativeUploadSpeedLimit() {
    return libtremotesfJNI.ServerSettings_alternativeUploadSpeedLimit(swigCPtr, this);
  }

  public boolean isAlternativeSpeedLimitsScheduled() {
    return libtremotesfJNI.ServerSettings_isAlternativeSpeedLimitsScheduled(swigCPtr, this);
  }

  public int alternativeSpeedLimitsBeginTime() {
    return libtremotesfJNI.ServerSettings_alternativeSpeedLimitsBeginTime(swigCPtr, this);
}

  public int alternativeSpeedLimitsEndTime() {
    return libtremotesfJNI.ServerSettings_alternativeSpeedLimitsEndTime(swigCPtr, this);
}

  public int alternativeSpeedLimitsDays() {
    return libtremotesfJNI.ServerSettings_alternativeSpeedLimitsDays(swigCPtr, this);
  }

  public int peerPort() {
    return libtremotesfJNI.ServerSettings_peerPort(swigCPtr, this);
  }

  public boolean isRandomPortEnabled() {
    return libtremotesfJNI.ServerSettings_isRandomPortEnabled(swigCPtr, this);
  }

  public boolean isPortForwardingEnabled() {
    return libtremotesfJNI.ServerSettings_isPortForwardingEnabled(swigCPtr, this);
  }

  public int encryptionMode() {
    return libtremotesfJNI.ServerSettings_encryptionMode(swigCPtr, this);
  }

  public boolean isUtpEnabled() {
    return libtremotesfJNI.ServerSettings_isUtpEnabled(swigCPtr, this);
  }

  public boolean isPexEnabled() {
    return libtremotesfJNI.ServerSettings_isPexEnabled(swigCPtr, this);
  }

  public boolean isDhtEnabled() {
    return libtremotesfJNI.ServerSettings_isDhtEnabled(swigCPtr, this);
  }

  public boolean isLpdEnabled() {
    return libtremotesfJNI.ServerSettings_isLpdEnabled(swigCPtr, this);
  }

  public int maximumPeersPerTorrent() {
    return libtremotesfJNI.ServerSettings_maximumPeersPerTorrent(swigCPtr, this);
  }

  public int maximumPeersGlobally() {
    return libtremotesfJNI.ServerSettings_maximumPeersGlobally(swigCPtr, this);
  }

  public ServerSettingsData data() {
    return new ServerSettingsData(libtremotesfJNI.ServerSettings_data(swigCPtr, this), false);
  }

}
