/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.equeim.libtremotesf;

public class SessionStats {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SessionStats(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SessionStats obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtremotesfJNI.delete_SessionStats(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long downloaded() {
    return libtremotesfJNI.SessionStats_downloaded(swigCPtr, this);
  }

  public long uploaded() {
    return libtremotesfJNI.SessionStats_uploaded(swigCPtr, this);
  }

  public int duration() {
    return libtremotesfJNI.SessionStats_duration(swigCPtr, this);
  }

  public int sessionCount() {
    return libtremotesfJNI.SessionStats_sessionCount(swigCPtr, this);
  }

}
