/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.equeim.libtremotesf;

public class SessionStats {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SessionStats(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SessionStats obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtremotesfJNI.delete_SessionStats(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long getDownloaded() {
    return libtremotesfJNI.SessionStats_downloaded_get(swigCPtr, this);
  }

  public long getUploaded() {
    return libtremotesfJNI.SessionStats_uploaded_get(swigCPtr, this);
  }

  public int getDuration() {
    return libtremotesfJNI.SessionStats_duration_get(swigCPtr, this);
  }

  public int getSessionCount() {
    return libtremotesfJNI.SessionStats_sessionCount_get(swigCPtr, this);
  }

}
