/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.equeim.libtremotesf;

public class StringsVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StringsVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringsVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtremotesfJNI.delete_StringsVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long size() {
    return libtremotesfJNI.StringsVector_size(swigCPtr, this);
  }

  public long capacity() {
    return libtremotesfJNI.StringsVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libtremotesfJNI.StringsVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libtremotesfJNI.StringsVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libtremotesfJNI.StringsVector_clear(swigCPtr, this);
  }

  public void add(String x) {
    libtremotesfJNI.StringsVector_add(swigCPtr, this, x);
  }

  public String get(int i) {
    return libtremotesfJNI.StringsVector_get(swigCPtr, this, i);
}

  public void set(int i, String val) {
    libtremotesfJNI.StringsVector_set(swigCPtr, this, i, val);
  }

}
