/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.equeim.libtremotesf;

public class TorrentFilesVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TorrentFilesVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TorrentFilesVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtremotesfJNI.delete_TorrentFilesVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long size() {
    return libtremotesfJNI.TorrentFilesVector_size(swigCPtr, this);
  }

  public long capacity() {
    return libtremotesfJNI.TorrentFilesVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libtremotesfJNI.TorrentFilesVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libtremotesfJNI.TorrentFilesVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libtremotesfJNI.TorrentFilesVector_clear(swigCPtr, this);
  }

  public void add(TorrentFile x) {
    libtremotesfJNI.TorrentFilesVector_add(swigCPtr, this, TorrentFile.getCPtr(x), x);
  }

  public TorrentFile get(int i) {
    long cPtr = libtremotesfJNI.TorrentFilesVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new TorrentFile(cPtr, true);
  }

  public void set(int i, TorrentFile val) {
    libtremotesfJNI.TorrentFilesVector_set(swigCPtr, this, i, TorrentFile.getCPtr(val), val);
  }

}
