/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.equeim.libtremotesf;

public class TrackersVector extends java.util.AbstractList<Tracker> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TrackersVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TrackersVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtremotesfJNI.delete_TrackersVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TrackersVector(Tracker[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Tracker element : initialElements) {
      add(element);
    }
  }

  public TrackersVector(Iterable<Tracker> initialElements) {
    this();
    for (Tracker element : initialElements) {
      add(element);
    }
  }

  public Tracker get(int index) {
    return doGet(index);
  }

  public Tracker set(int index, Tracker e) {
    return doSet(index, e);
  }

  public boolean add(Tracker e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Tracker e) {
    modCount++;
    doAdd(index, e);
  }

  public Tracker remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public TrackersVector() {
    this(libtremotesfJNI.new_TrackersVector__SWIG_0(), true);
  }

  public TrackersVector(TrackersVector other) {
    this(libtremotesfJNI.new_TrackersVector__SWIG_1(TrackersVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return libtremotesfJNI.TrackersVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libtremotesfJNI.TrackersVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libtremotesfJNI.TrackersVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libtremotesfJNI.TrackersVector_clear(swigCPtr, this);
  }

  public TrackersVector(int count, Tracker value) {
    this(libtremotesfJNI.new_TrackersVector__SWIG_2(count, Tracker.getCPtr(value), value), true);
  }

  private int doSize() {
    return libtremotesfJNI.TrackersVector_doSize(swigCPtr, this);
  }

  private void doAdd(Tracker x) {
    libtremotesfJNI.TrackersVector_doAdd__SWIG_0(swigCPtr, this, Tracker.getCPtr(x), x);
  }

  private void doAdd(int index, Tracker x) {
    libtremotesfJNI.TrackersVector_doAdd__SWIG_1(swigCPtr, this, index, Tracker.getCPtr(x), x);
  }

  private Tracker doRemove(int index) {
    return new Tracker(libtremotesfJNI.TrackersVector_doRemove(swigCPtr, this, index), true);
  }

  private Tracker doGet(int index) {
    return new Tracker(libtremotesfJNI.TrackersVector_doGet(swigCPtr, this, index), false);
  }

  private Tracker doSet(int index, Tracker val) {
    return new Tracker(libtremotesfJNI.TrackersVector_doSet(swigCPtr, this, index, Tracker.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    libtremotesfJNI.TrackersVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
