/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.equeim.libtremotesf;

public class TrackersVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TrackersVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TrackersVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtremotesfJNI.delete_TrackersVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long size() {
    return libtremotesfJNI.TrackersVector_size(swigCPtr, this);
  }

  public long capacity() {
    return libtremotesfJNI.TrackersVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libtremotesfJNI.TrackersVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libtremotesfJNI.TrackersVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libtremotesfJNI.TrackersVector_clear(swigCPtr, this);
  }

  public void add(Tracker x) {
    libtremotesfJNI.TrackersVector_add(swigCPtr, this, Tracker.getCPtr(x), x);
  }

  public Tracker get(int i) {
    long cPtr = libtremotesfJNI.TrackersVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Tracker(cPtr, true);
  }

  public void set(int i, Tracker val) {
    libtremotesfJNI.TrackersVector_set(swigCPtr, this, i, Tracker.getCPtr(val), val);
  }

}
