/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.equeim.libtremotesf;

public class Tracker {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Tracker(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Tracker obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtremotesfJNI.delete_Tracker(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int id() {
    return libtremotesfJNI.Tracker_id(swigCPtr, this);
  }

  public String announce() {
    return libtremotesfJNI.Tracker_announce(swigCPtr, this);
}

  public String site() {
    return libtremotesfJNI.Tracker_site(swigCPtr, this);
}

  public int status() {
    return libtremotesfJNI.Tracker_status(swigCPtr, this);
  }

  public String errorMessage() {
    return libtremotesfJNI.Tracker_errorMessage(swigCPtr, this);
}

  public int peers() {
    return libtremotesfJNI.Tracker_peers(swigCPtr, this);
  }

  public long nextUpdateTime() {
    return libtremotesfJNI.Tracker_nextUpdateTime(swigCPtr, this);
  }

  public int nextUpdateEta() {
    return libtremotesfJNI.Tracker_nextUpdateEta(swigCPtr, this);
  }

  public final static class Status {
    public final static int Inactive = 0;
    public final static int Active = Inactive + 1;
    public final static int Queued = Active + 1;
    public final static int Updating = Queued + 1;
    public final static int Error = Updating + 1;
  }

}
